#!/bin/sh
# build-config.sh — generates config.js at Netlify build time
# from public environment variables.
#
# IMPORTANT: only PUBLIC keys go here. Secrets (ANTHROPIC_API_KEY,
# RAZORPAY_KEY_SECRET) must NEVER appear in this file — they stay
# server-side in Netlify Functions only.
#
# This file is safe to commit to git. The generated config.js
# is git-ignored and produced fresh on every deploy.

set -eu

# Fail loudly if a required public env var is missing — prevents silent
# deploys with broken auth.
: "${SUPA_URL:?SUPA_URL environment variable not set in Netlify}"
: "${SUPA_ANON:?SUPA_ANON environment variable not set in Netlify}"
: "${RAZORPAY_KEY_ID:?RAZORPAY_KEY_ID environment variable not set in Netlify}"

cat > config.js <<EOF
// Generated by build-config.sh at deploy time. DO NOT EDIT.
// DO NOT COMMIT. This file is reproduced from Netlify env vars on every build.
window.ENG_CONFIG = {
  SUPA_URL:        "${SUPA_URL}",
  SUPA_ANON:       "${SUPA_ANON}",
  RAZORPAY_KEY_ID: "${RAZORPAY_KEY_ID}"
};
EOF

echo "✓ config.js generated ($(wc -c < config.js) bytes)"
